### ISSUE TITLE
Memory leak related to Renderer.render() method

### ISSUE THREAD

**Issue by beewyka819** [Yatekii/imgui-wgpu-rs#21] opened 2020-09-03 01:55 UTC
In the latest commit, it appears calling Renderer's render() method introduces some form of memory leak on my system. This can even be seen when running the provided examples. If the method call is present, memory usage will constantly climb. Removing the call fixes the memory leak but obviously then you can't render the GUI.

I'm currently running on Windows 1909 with rustc 1.45.1 and NVIDIA drivers 452.06 on an RTX 2070.

EDIT: Currently trying to figure out how to profile it since a friend doesn't experience the leak on his system.

**Comment by beewyka819** [comment] 2020-09-03 03:35
Upon doing some profiling in Visual Studio, it appears the leak is related to upload_index_buffer(), upload_vertex_buffer(), and update_uniform_buffer() (Couldn't figure out how to export the heap snapshot, so here's a screenshot : https://i.imgur.com/DRIsHLc.png). Could this be an issue related to the vulkan backend of wgpu-rs rather than a problem with this crate?

**Comment by beewyka819** [comment] 2020-09-04 19:11
Interestingly enough it appears to only leak in debug mode. When compiling in release the issue is seemingly gone.

**Comment by Yatekii** [comment] 2020-09-08 20:47
Hmm odd, I never noticed ... Is this some new occurence?
Does this happen with Vulkan/Metal too?

I'll have to conduct some experiments, but maybe some1 else already knows :)

**Comment by beewyka819** [comment] 2020-09-08 20:50
Yeah it happens with Vulkan (haven't tested metal), but it's not as bad as with DX11 and DX12, which have much worse leaks. Again, it seems to not happen on my friends Arch install, so could be an OS specific issue, or possibly even a driver or hardware specific issue. Definitely strange though.

**Comment by cwfitzgerald** [comment] 2020-10-13 12:27
Does this still happen with the latest wgpu 0.6 ports? I know that wgpu had some leak issues in 0.5 when using create_buffer_with_data.

**Comment by beewyka819** [comment] 2021-03-01 18:20
Just saw this. I've been busy with classes the past two semesters and haven't really had time to follow up on this. Whenever I get the chance I'll try porting my project to 0.7 and see if it helps.

**Comment by francesco-cattoglio** [comment] 2021-03-15 20:45
I think I might be experiencing the same issue under DX12 with the latest wgpu master, I am seeing the memory usage of my program grow very quickly, around 100MB/s, even when idling. According to task manager, GPU memory is growing as well. I will see if the same "only leaks on debug" behavior is present in my code as well, and will report back.

**Comment by francesco-cattoglio** [comment] 2021-03-17 15:48
I can confirm that using latest wgpu-rs fixes the memory leak. The first commit that fixed the issue is https://github.com/gfx-rs/wgpu-rs/commit/66b900bf8d3e10e8fcb5a37200a69c057c27a7a5

**Comment by cwfitzgerald** [comment] 2021-03-17 16:26
Awesome! Closing as out of scope. Feel free to reopen once another leak is found.

**Closed by cwfitzgerald** 2021-03-17 16:26 UTC
